model:
  embedding_dim: 128
  lstm_units: 100
  epochs: 300
  batch_size: 16
  path: lstm_model.h5
data:
  normal: resource/logs/normal_log.csv
  abnormal: resource/logs/abnormal_log.csv
  sequence_log: resource/logs/normal_log.csv
sequence_model:
  units: 100
  dropout: 0.0
  epochs: 20
  second_lstm: false
  path: seq_model.h5
GPU: null
